[[FLANN]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a9c2cecb4782453419f5d8efc08ea3e9c95e508"
libc = "glibc"
os = "linux"

    [[FLANN.download]]
    sha256 = "abfbfca5b06b181cb96afe4a23693fb1dabcc233e0e0b9dfa67ac8edc1ea8595"
    url = "https://github.com/JuliaBinaryWrappers/FLANN_jll.jl/releases/download/FLANN-v1.9.1+0/FLANN.v1.9.1.aarch64-linux-gnu-cxx03.tar.gz"
[[FLANN]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e63c4f5c38ab91ca66bebf281273291c355370f"
libc = "glibc"
os = "linux"

    [[FLANN.download]]
    sha256 = "ece9e5b910377b0f4906731f7157043799f6672c2709ea82b7541d96fe07c84a"
    url = "https://github.com/JuliaBinaryWrappers/FLANN_jll.jl/releases/download/FLANN-v1.9.1+0/FLANN.v1.9.1.aarch64-linux-gnu-cxx11.tar.gz"
[[FLANN]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3aecef48c2172205f70308dd6cedb65295e2f76c"
libc = "musl"
os = "linux"

    [[FLANN.download]]
    sha256 = "bb38334d37a2946682b1d8fa0eae4eb889c9642776ed4f3944b5b2e38df66cac"
    url = "https://github.com/JuliaBinaryWrappers/FLANN_jll.jl/releases/download/FLANN-v1.9.1+0/FLANN.v1.9.1.aarch64-linux-musl-cxx03.tar.gz"
[[FLANN]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a9b95f779880d45a4dd5d8f682e72465043fcb83"
libc = "musl"
os = "linux"

    [[FLANN.download]]
    sha256 = "0e4916f28cdf2260545517e732aab66429f2f7fa5e8e71d15acc95033d9e6f91"
    url = "https://github.com/JuliaBinaryWrappers/FLANN_jll.jl/releases/download/FLANN-v1.9.1+0/FLANN.v1.9.1.aarch64-linux-musl-cxx11.tar.gz"
[[FLANN]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "64bde3502e807fdf2a9b7ecb5fe9eca5b7cad40a"
libc = "glibc"
os = "linux"

    [[FLANN.download]]
    sha256 = "d3b7d4e5a25e8a931c2d09f281b418445d363c498a0f815180739f4d281f3cd4"
    url = "https://github.com/JuliaBinaryWrappers/FLANN_jll.jl/releases/download/FLANN-v1.9.1+0/FLANN.v1.9.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[FLANN]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a5fe2b0d8081fc2339bfa2fe61304978d669f0b0"
libc = "glibc"
os = "linux"

    [[FLANN.download]]
    sha256 = "5e4ae8bbf94740b28b515631e4f96c52e57aa2d21104ecfa0ade78e4ad6091fb"
    url = "https://github.com/JuliaBinaryWrappers/FLANN_jll.jl/releases/download/FLANN-v1.9.1+0/FLANN.v1.9.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[FLANN]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad88d88c6b0c411194f107e98f23893de78b5be6"
libc = "musl"
os = "linux"

    [[FLANN.download]]
    sha256 = "29c8a7c2eebb0f8b8ff0bf1a32db75955aedb78de45423c92f3800793ddfebdc"
    url = "https://github.com/JuliaBinaryWrappers/FLANN_jll.jl/releases/download/FLANN-v1.9.1+0/FLANN.v1.9.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[FLANN]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18aade2bfd70d1c897cbfa1eb58a23ead2336f2d"
libc = "musl"
os = "linux"

    [[FLANN.download]]
    sha256 = "b52490b16eaca6037c758037e5d1ddd6f041b9e0e170493be9469398d4737505"
    url = "https://github.com/JuliaBinaryWrappers/FLANN_jll.jl/releases/download/FLANN-v1.9.1+0/FLANN.v1.9.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[FLANN]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "550a50e12be5438ab15992bf6d8009fd6d848523"
libc = "glibc"
os = "linux"

    [[FLANN.download]]
    sha256 = "59f77b178c95f7f58b54c2ecfd99799574d5e7fa8b25d64dac4456ea3c952cf2"
    url = "https://github.com/JuliaBinaryWrappers/FLANN_jll.jl/releases/download/FLANN-v1.9.1+0/FLANN.v1.9.1.i686-linux-gnu-cxx03.tar.gz"
[[FLANN]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc14379663073c3542e3d44ea1bf93fd2c9bb4ce"
libc = "glibc"
os = "linux"

    [[FLANN.download]]
    sha256 = "1707cfce8cc2d100fb3c94ae4c83de6a0348a0f4bf7eb5c2bfa05756f98d05ba"
    url = "https://github.com/JuliaBinaryWrappers/FLANN_jll.jl/releases/download/FLANN-v1.9.1+0/FLANN.v1.9.1.i686-linux-gnu-cxx11.tar.gz"
[[FLANN]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2cbf619e6401c45ef97bda8d3b4a2530d51ed105"
libc = "musl"
os = "linux"

    [[FLANN.download]]
    sha256 = "77290c490fc0a639618fb3b40d8c707b7ef2b720bb4f6c427ff63687b2a86180"
    url = "https://github.com/JuliaBinaryWrappers/FLANN_jll.jl/releases/download/FLANN-v1.9.1+0/FLANN.v1.9.1.i686-linux-musl-cxx03.tar.gz"
[[FLANN]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "783bf9959a023f539eec4ea0b48c917e03462fc9"
libc = "musl"
os = "linux"

    [[FLANN.download]]
    sha256 = "6ddc77f1570f81f2fffd0d27c06303f00f36905ee49af26428ae9fc1951568ca"
    url = "https://github.com/JuliaBinaryWrappers/FLANN_jll.jl/releases/download/FLANN-v1.9.1+0/FLANN.v1.9.1.i686-linux-musl-cxx11.tar.gz"
[[FLANN]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cdb9a72898393bc8e67bc97da041ab7d3d75a2ce"
os = "windows"

    [[FLANN.download]]
    sha256 = "2eff7752b326022feeba86d8612dbfa016847838b999e9fac72a04dba189506e"
    url = "https://github.com/JuliaBinaryWrappers/FLANN_jll.jl/releases/download/FLANN-v1.9.1+0/FLANN.v1.9.1.i686-w64-mingw32-cxx03.tar.gz"
[[FLANN]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "199e560aacecb45ff3d098442f7699ad2d908dcb"
os = "windows"

    [[FLANN.download]]
    sha256 = "8ffb597e44e659ce1f3af06e8453bfd403746d485a9be26bba38b8f365bf7576"
    url = "https://github.com/JuliaBinaryWrappers/FLANN_jll.jl/releases/download/FLANN-v1.9.1+0/FLANN.v1.9.1.i686-w64-mingw32-cxx11.tar.gz"
[[FLANN]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "570cf823b4f507904d025b0562687e403f67f94a"
libc = "glibc"
os = "linux"

    [[FLANN.download]]
    sha256 = "a9261672678589d91227d505d4655616585fd5e117dae0fcc769445518dbfae3"
    url = "https://github.com/JuliaBinaryWrappers/FLANN_jll.jl/releases/download/FLANN-v1.9.1+0/FLANN.v1.9.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[FLANN]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f60f459810333b605c1d2ce836d33d878d0aac4e"
libc = "glibc"
os = "linux"

    [[FLANN.download]]
    sha256 = "308c6becb23660211b5d24ed930ba5d2e5318bd3bbbf2c5fd7c7b403b6d8b178"
    url = "https://github.com/JuliaBinaryWrappers/FLANN_jll.jl/releases/download/FLANN-v1.9.1+0/FLANN.v1.9.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[FLANN]]
arch = "x86_64"
git-tree-sha1 = "c06046b1d4b7bf78f6692a927e5a4fed2ec18e90"
os = "macos"

    [[FLANN.download]]
    sha256 = "69a8b451f472553c3395f01e123fc3e2d34e0ddbee06a8a5f35bcb19f931b92f"
    url = "https://github.com/JuliaBinaryWrappers/FLANN_jll.jl/releases/download/FLANN-v1.9.1+0/FLANN.v1.9.1.x86_64-apple-darwin.tar.gz"
[[FLANN]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "019a4835c760a8562538537fab751273f2a6c8df"
libc = "glibc"
os = "linux"

    [[FLANN.download]]
    sha256 = "78de5be325b50323e5031f8488926e87dac1a3bcdc0fd73e287bdc9c66acdd6d"
    url = "https://github.com/JuliaBinaryWrappers/FLANN_jll.jl/releases/download/FLANN-v1.9.1+0/FLANN.v1.9.1.x86_64-linux-gnu-cxx03.tar.gz"
[[FLANN]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e8cdeb6d772f56db880b31d2b27a38280efc8a6"
libc = "glibc"
os = "linux"

    [[FLANN.download]]
    sha256 = "f23fce225f44da4a65d79ce047fe2d7b0c941d9db00f65c78cb96eb0b7f21c08"
    url = "https://github.com/JuliaBinaryWrappers/FLANN_jll.jl/releases/download/FLANN-v1.9.1+0/FLANN.v1.9.1.x86_64-linux-gnu-cxx11.tar.gz"
[[FLANN]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d15c610a2e741ae4211a25a50a51a075dca3f105"
libc = "musl"
os = "linux"

    [[FLANN.download]]
    sha256 = "6d6ff3b599e7ae5212e163eafac180da35da1ced4c2aa5d5698aaec874f38ce7"
    url = "https://github.com/JuliaBinaryWrappers/FLANN_jll.jl/releases/download/FLANN-v1.9.1+0/FLANN.v1.9.1.x86_64-linux-musl-cxx03.tar.gz"
[[FLANN]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f02525f06da228dcfb285d1d91e80f8af6808025"
libc = "musl"
os = "linux"

    [[FLANN.download]]
    sha256 = "46038930fec3c06e6299ba159b245f3f323daf0cca7b54b9ab823617f411aacb"
    url = "https://github.com/JuliaBinaryWrappers/FLANN_jll.jl/releases/download/FLANN-v1.9.1+0/FLANN.v1.9.1.x86_64-linux-musl-cxx11.tar.gz"
[[FLANN]]
arch = "x86_64"
git-tree-sha1 = "6422107f877914517c6cf531eb234ccf970d1122"
os = "freebsd"

    [[FLANN.download]]
    sha256 = "88cfdac054324a1798d14a2b5e34cb8fac2a2e1a59b83b4f549e579e393dc511"
    url = "https://github.com/JuliaBinaryWrappers/FLANN_jll.jl/releases/download/FLANN-v1.9.1+0/FLANN.v1.9.1.x86_64-unknown-freebsd.tar.gz"
[[FLANN]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91f3b59f860aaf3ff242fdd53035d9518e9f14a8"
os = "windows"

    [[FLANN.download]]
    sha256 = "6c7d80cd7f94160bd7d96588b5ccd11b3e31cf2b2f328707719ec4f8d92fd3eb"
    url = "https://github.com/JuliaBinaryWrappers/FLANN_jll.jl/releases/download/FLANN-v1.9.1+0/FLANN.v1.9.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[FLANN]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "542689efee801c98e716edac775757d9b0816521"
os = "windows"

    [[FLANN.download]]
    sha256 = "e588eacd9e49793ea475be1314290869e2074768267c8766fda69718bfacc48f"
    url = "https://github.com/JuliaBinaryWrappers/FLANN_jll.jl/releases/download/FLANN-v1.9.1+0/FLANN.v1.9.1.x86_64-w64-mingw32-cxx11.tar.gz"
