# Autogenerated wrapper script for FLANN_jll for x86_64-apple-darwin
export libflann, libflann_cpp

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("FLANN")
JLLWrappers.@declare_library_product(libflann, "@rpath/libflann.1.9.dylib")
JLLWrappers.@declare_library_product(libflann_cpp, "@rpath/libflann_cpp.1.9.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libflann,
        "lib/libflann.1.9.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libflann_cpp,
        "lib/libflann_cpp.1.9.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
